# Basic Python

## 1. Split this string

In [14]:
s = "Hi there Sam!"

In [2]:
s=s.split("r")

print(s)

['Hi the', 'e Sam!']


## 2. Use .format() to print the following string. 

### Output should be: The diameter of Earth is 12742 kilometers.

In [3]:
planet = "Earth"
diameter = 12742

In [4]:
op="The diameter of {} is {} kilometers.".format(planet, diameter)

print(op)

The diameter of Earth is 12742 kilometers.


## 3. In this nest dictionary grab the word "hello"

In [5]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}

In [6]:
print(d['k1'][3]['tricky'][3]['target'][3])

hello


# Numpy

In [7]:
import numpy as np

## 4.1 Create an array of 10 zeros? 
## 4.2 Create an array of 10 fives?

In [8]:
#4.1 answer:

arr=np.zeros(10)

print(arr)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [9]:
#4.2 answer:

arr=np.ones(10)*5

print(arr)

[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


## 5. Create an array of all the even integers from 20 to 35

In [10]:
arr=np.arange(20,36,2)

print(arr)

[20 22 24 26 28 30 32 34]


## 6. Create a 3x3 matrix with values ranging from 0 to 8

In [11]:
arr = np.arange(0,9).reshape(3,3)

print(arr)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


## 7. Concatinate a and b 
## a = np.array([1, 2, 3]), b = np.array([4, 5, 6])

In [13]:
a=np.array([1,2,3])
b=np.array([4,5,6])

c=np.concatenate((a,b))
print(c)

[1 2 3 4 5 6]


# Pandas

## 8. Create a dataframe with 3 rows and 2 columns

In [14]:
import pandas as pd


In [15]:
s1=pd.Series(np.random.random(2))
s2=pd.Series(np.random.random(2))
s3=pd.Series(np.random.random(2))

a=pd.DataFrame([s1,s2,s3])
a

0         1
0  0.725444  0.455576
1  0.969961  0.296612
2  0.066419  0.038752

## 9. Generate the series of dates from 1st Jan, 2023 to 10th Feb, 2023

In [16]:
dt = pd.date_range("2023-01-01" , periods=41,freq="D")
ts=pd.Series(range(len(dt)),index=dt)
print(ts)

2023-01-01     0
2023-01-02     1
2023-01-03     2
2023-01-04     3
2023-01-05     4
2023-01-06     5
2023-01-07     6
2023-01-08     7
2023-01-09     8
2023-01-10     9
2023-01-11    10
2023-01-12    11
2023-01-13    12
2023-01-14    13
2023-01-15    14
2023-01-16    15
2023-01-17    16
2023-01-18    17
2023-01-19    18
2023-01-20    19
2023-01-21    20
2023-01-22    21
2023-01-23    22
2023-01-24    23
2023-01-25    24
2023-01-26    25
2023-01-27    26
2023-01-28    27
2023-01-29    28
2023-01-30    29
2023-01-31    30
2023-02-01    31
2023-02-02    32
2023-02-03    33
2023-02-04    34
2023-02-05    35
2023-02-06    36
2023-02-07    37
2023-02-08    38
2023-02-09    39
2023-02-10    40
Freq: D, dtype: int64


## 10. Create 2D list to DataFrame

lists = [[1, 'aaa', 22],
         [2, 'bbb', 25],
         [3, 'ccc', 24]]

In [17]:
lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]

In [18]:
df=pd.DataFrame(lists,columns=['S.No','Name','Age'])
 
print(df)

   S.No Name  Age
0     1  aaa   22
1     2  bbb   25
2     3  ccc   24
